### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "signup92@signup.com",
    "password":"12345678"
}

### Signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "signup92@signup.com",
    "password":"12345678"
}

### Current user
GET http://localhost:3000/auth/whoami

### Signout
POST http://localhost:3000/auth/signout


### Set a color
GET http://localhost:3000/auth/colors/red


### Get the color
GET http://localhost:3000/auth/colors




### Find a particular user with id

Get http://localhost:3000/auth/2



### Find all user with a given email

Get http://localhost:3000/auth?email=test@test.com




### Delete a user with a given id

Delete http://localhost:3000/auth/1




### Update a user with a given id

Patch http://localhost:3000/auth/2
content-type: application/json

{
    "email": "updated@updated.com"
   
}




